POWEBI_TENANT_ID: 
POWERBI_APP: 
POWERBI_DATASET_ID: 
POWERBI_PASSWORD: 
POWERBI_USERNAME: 
SNOWFLAKE_ACCOUNT: 
SNOWFLAKE_DATABASE: 
SNOWFLAKE_PASSWORD: 
SNOWFLAKE_REGION: 
SNOWFLAKE_ROLE: 
SNOWFLAKE_SCHEMA: 
SNOWFLAKE_USERNAME: 
SNOWFLAKE_WAREHOUSE: 
